### ISSUE TITLE
不存在该模板

### ISSUE THREAD

**Issue by UWDBW** [BeiYazi0/Img_Mix#1]
下载完之后我查模板1，告诉我不存在该模板，但是我去找MASK，发现里面确实有原来就有的黑白图片

**Comment by BeiYazi0** [comment]
可以上传图片复现吗？
或者将__init__.py第116行查找模板失败时发送的内容换成变量mask_file，自行测试一下。

**Comment by UWDBW** [comment]
> 可以上传图片复现吗？ 或者将__init__.py第116行查找模板失败时发送的内容换成变量mask_file，自行测试一下。

我上传模板也跟我说参数错误

**Comment by UWDBW** [comment]
> 可以上传图片复现吗？ 或者将__init__.py第116行查找模板失败时发送的内容换成变量mask_file，自行测试一下。

ev换成mask_file就是程序报错，什么都发不出来

**Comment by BeiYazi0** [comment]
> > 可以上传图片复现吗？ 或者将__init__.py第116行查找模板失败时发送的内容换成变量mask_file，自行测试一下。
> 
> ev换成mask_file就是程序报错，什么都发不出来

我没说清楚，是把“不存在该模板”这部分换成mask_file

**Comment by BeiYazi0** [comment]
> > 可以上传图片复现吗？ 或者将__init__.py第116行查找模板失败时发送的内容换成变量mask_file，自行测试一下。
> 
> 我上传模板也跟我说参数错误

添加模板报参数错误，可能是“添加模板”后面没有跟生成的模板序号，或者缺少图片，完整的指令比如“添加模板100[图片]”

**Comment by UWDBW** [comment]
> > > 可以上传图片复现吗？ 或者将__init__.py第116行查找模板失败时发送的内容换成变量mask_file，自行测试一下。
> > 
> > 
> > 我上传模板也跟我说参数错误
> 
> 添加模板报参数错误，可能是“添加模板”后面没有跟生成的模板序号，或者缺少图片，完整的指令比如“添加模板100[图片]”

输出是图片路径

**Comment by UWDBW** [comment]
> > > 可以上传图片复现吗？ 或者将__init__.py第116行查找模板失败时发送的内容换成变量mask_file，自行测试一下。
> > 
> > 
> > 我上传模板也跟我说参数错误
> 
> 添加模板报参数错误，可能是“添加模板”后面没有跟生成的模板序号，或者缺少图片，完整的指令比如“添加模板100[图片]”

输出是图片的路径，路径里面有1.jpg

**Comment by UWDBW** [comment]
> > > 可以上传图片复现吗？ 或者将__init__.py第116行查找模板失败时发送的内容换成变量mask_file，自行测试一下。
> > 
> > 
> > 我上传模板也跟我说参数错误
> 
> 添加模板报参数错误，可能是“添加模板”后面没有跟生成的模板序号，或者缺少图片，完整的指令比如“添加模板100[图片]”
我就是这样添加的

**Comment by BeiYazi0** [comment]
好吧，添加模板那个是因为代码中参数数量判定错了，已经对仓库进行了修改。但查模板我这边一直是正常的，我也不明白原因了。

**Comment by UWDBW** [comment]
刚刚添加模板能复现出来，然后我去看了一下
1、我添加的模板是在modules文件夹下面的，也就是说我的添加的跟Img_Mix是在同一个文件目录下的
2、这个添加的图片它的名字就是"Img_Mix\images\mask\数字.jpg"，是前面的路径是图片的名字而不是真实的路径
至于查模板，因为新添加的能查到，所以可能查模板的方式有问题？根据添加图片的来看，可能是在跟Img_Mix同一个文件夹内查找带路径名字的图片，所以查找不到？

**Comment by BeiYazi0** [comment]
我大概明白原因了，路径中双斜杠部分被转义了，可能是python版本问题，以后再也不拼接字符串了，还是用path.join拼路径吧。
把路径双斜杠换成反向单斜杠或许能解决

**Comment by BeiYazi0** [comment]
转义后也应该是正确的路径呀，不明白为啥会把斜杠作为文件名的一部分，windows系统文件名是不能包含斜杠的，难道你不是win

**Comment by UWDBW** [comment]
> 转义后也应该是正确的路径呀，不明白为啥会把斜杠作为文件名的一部分，windows系统文件名是不能包含斜杠的，难道你不是win

破案了，我是linux的

**Comment by BeiYazi0** [comment]
这样看来还是得用path.join拼路径才行，不能字符串直接拼接

**Comment by BeiYazi0** [comment]
修改了一下，大概没有问题了吧

**Comment by UWDBW** [comment]
> 修改了一下，大概没有问题了吧

试了下，OK
